# Generated by Django 4.0.3 on 2022-04-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myportfolioprojectmodel',
            old_name='to_fill_the_pull',
            new_name='to_fill_the_pool',
        ),
    ]
