# Generated by Django 4.0.4 on 2022-04-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0002_rename_to_fill_the_pull_myportfolioprojectmodel_to_fill_the_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myportfolioprojectmodel',
            old_name='to_fill_the_pool',
            new_name='entry_date',
        ),
    ]
