# Generated by Django 4.0.4 on 2022-04-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0003_rename_to_fill_the_pool_myportfolioprojectmodel_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myportfolioprojectmodel',
            name='exchanges',
        ),
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='exchanges',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='ExchangeModel',
        ),
    ]
