# Generated by Django 3.2.12 on 2022-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0003_rename_to_fill_the_pool_myportfolioprojectmodel_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfolioprojectmodel',
            name='exchanges',
            field=models.ManyToManyField(null=True, to='defipool.ExchangeModel'),
        ),
    ]
