# Generated by Django 3.2.12 on 2022-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0004_alter_myportfolioprojectmodel_exchanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfolioprojectmodel',
            name='exchanges',
            field=models.ManyToManyField(blank=True, to='defipool.ExchangeModel'),
        ),
    ]
