# Generated by Django 4.0.4 on 2022-04-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0004_remove_myportfolioprojectmodel_exchanges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='claim_address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='claim_network',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='cmc_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='pool_address',
            field=models.CharField(default='', max_length=400),
        ),
    ]
