# Generated by Django 3.2.12 on 2022-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0005_alter_myportfolioprojectmodel_exchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='claim_address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='claim_network',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='pool_address',
            field=models.CharField(default='', max_length=400),
        ),
    ]
