# Generated by Django 3.2.12 on 2022-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0006_auto_20220416_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolioprojectmodel',
            name='cmc_id',
            field=models.IntegerField(default=0),
        ),
    ]
