# Generated by Django 3.2.12 on 2022-04-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0007_myportfolioprojectmodel_cmc_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preidohistorymodel',
            options={'ordering': ('-id',), 'verbose_name': 'Pre IDO', 'verbose_name_plural': 'Pre IDO'},
        ),
    ]
