# Generated by Django 3.2.12 on 2022-04-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defipool', '0008_alter_preidohistorymodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentprojectmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Новый проект', 'verbose_name_plural': 'Новый проект'},
        ),
        migrations.AlterModelOptions(
            name='myportfolioprojectmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
    ]
